version: '3.9'  

services:

  drupal:
    image: drupal:8.8.2
    ports: 
      - 8080:80

  postgres:
    image: postgres:12.1
    environment: 
      - POSTGRES_DB=drupal
      - POSTGRES_USER=user
      - POSTGRES_PASSWRD=pass

