# create your drupal and postgres config here, based off the last assignment
version: '3.9'  

services:

  drupal:
    image: custom-drupal
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - 8080:80
    volumes:
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles       
      - drupal-sites:/var/www/html/sites      
      - drupal-themes:/var/www/html/themes

  postgres:
    image: postgres:12.1
    environment: 
      - POSTGRES_DB=drupal
      - POSTGRES_USER=user
      - POSTGRES_PASSWRD=pass
    volumes:
      - drupal-data:/var/lib/postgresql/data

volumes:
  drupal-data:
  drupal-modules:
  drupal-profiles:
  drupal-sites:
  drupal-themes: